language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
sudo: false
cache:
  directories:
    - $HOME/buildout-cache
    - $HOME/parts/node
env:
  matrix:
    - CONF=travis.cfg
matrix:
  allow_failures:
    - python: 3.4

install:
  - pip install -U pip
  - python bootstrap-buildout.py
  - bin/buildout -c $CONF annotate
  - bin/buildout -N -t 3 -c $CONF
script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/createcoverage run bin/test
  - pip install coverage==4.4 coveralls
  - coveralls
after_failure:
  - bin/flake8 --version